import React from "react";

const MLBPlayerContext = React.createContext({
    BatHand: '',
    BirthCity: '',
    BirthCountry: '',
    BirthDate: '',
    BirthState: '',
    College: '',
    DraftKingsName: '',
    DraftKingsPlayerID: '',
    Experience: '',
    FanDuelName: '',
    FanDuelPlayerID: '',
    FantasyAlarmPlayerID: '',
    FantasyDraftName: '',
    FantasyDraftPlayerID: '',
    FirstName: '',
    GlobalTeamID: '',
    Height: '',
    HighSchool: '',
    InjuryBodyPart: '',
    InjuryNotes: '',
    InjuryStartDate: '',
    InjuryStatus: '',
    Jersey: '',
    LastName: '',
    MLBAMID: '',
    PhotoUrl: '',
    PlayerID: '',
    Position: '',
    PositionCategory: '',
    ProDebut: '',
    RotoWirePlayerID: '',
    RotoworldPlayerID: '',
    Salary: '',
    SportRadarPlayerID: '',
    SportsDataID: '',
    SportsDirectPlayerID: '',
    StatsPlayerID: '',
    Status: '',
    Team: '',
    TeamID: '',
    ThrowHand: '',
    UpcomingGameID: '',
    UsaTodayHeadshotNoBackgroundUpdated: '',
    UsaTodayHeadshotNoBackgroundUrl: '',
    UsaTodayHeadshotUpdated: '',
    UsaTodayHeadshotUrl: '',
    UsaTodayPlayerID: '',
    Weight: '',
    XmlTeamPlayerID: '',
    YahooName: '',
    YahooPlayerID: '',
});

export default MLBPlayerContext;