import React from "react";

const NBAPlayerContext = React.createContext({
  PlayerID: '',
  SportsDataID: '',
  Status: '',
  TeamID: '',
  Team: '',
  Jersey: '',
  PositionCategory: '',
  Position: '',
  FirstName: '',
  LastName: '',
  Height: '',
  Weight: '',
  BirthDate: '',
  BirthCity: '',
  BirthState: '',
  BirthCountry: '',
  HighSchool: '',
  College: '',
  Salary: '',
  PhotoUrl: '',
  Experience: '',
  SportRadarPlayerID: '',
  RotoworldPlayerID: '',
  RotoWirePlayerID: '',
  FantasyAlarmPlayerID: '',
  StatsPlayerID: '',
  SportsDirectPlayerID: '',
  XmlTeamPlayerID: '',
  InjuryStatus: '',
  InjuryBodyPart: '',
  InjuryStartDate: '',
  InjuryNotes: '',
  FanDuelPlayerID: '',
  DraftKingsPlayerID: '',
  YahooPlayerID: '',
  FanDuelName: '',
  DraftKingsName: '',
  YahooName: '',
  DepthChartPosition: '',
  DepthChartOrder: '',
  GlobalTeamID: '',
  FantasyDraftName: '',
  FantasyDraftPlayerID: '',
  UsaTodayPlayerID: '',
  UsaTodayHeadshotUrl: '',
  UsaTodayHeadshotNoBackgroundUrl: '',
  UsaTodayHeadshotUpdated: '',
  UsaTodayHeadshotNoBackgroundUpdated: '',
  NbaDotComPlayerID: ''
});

export default NBAPlayerContext;