import React from "react";

const NHLPlayerContext = React.createContext({
  PlayerID: '',
  FirstName: '',
  LastName: '',
  Status: '',
  TeamID: '',
  Team: '',
  Position: '',
  Jersey: '',
  Catches: '',
  Shoots: '',
  Height: '',
  Weight: '',
  BirthDate: '',
  BirthCity: '',
  BirthState: '',
  PhotoUrl: '',
  SportRadarPlayerID: '',
  RotoworldPlayerID: '',
  RotoWirePlayerID: '',
  FantasyAlarmPlayerID: '',
  StatsPlayerID: '',
  SportsDirectPlayerID: '',
  XmlTeamPlayerID: '',
  InjuryStatus: '',
  InjuryBodyPart: '',
  InjuryStartDate: '',
  InjuryNotes: '',
  FanDuelPlayerID: '',
  DraftKingsPlayerID: '',
  YahooPlayerID: '',
  FanDuelName: '',
  DraftKingsName: '',
  YahooName: '',
  DepthChartPosition: '',
  DepthChartOrder: '',
  GlobalTeamID: '',
  FantasyDraftName: '',
  FantasyDraftPlayerID: '',
  UsaTodayPlayerID: '',
  UsaTodayHeadshotUrl: '',
  UsaTodayHeadshotNoBackgroundUrl: '',
  UsaTodayHeadshotUpdated: '',
  UsaTodayHeadshotNoBackgroundUpdated: '',
});

export default NHLPlayerContext;
